package com.medisys.model;

import javafx.beans.property.SimpleStringProperty;

public class Doctor extends User {
    private final SimpleStringProperty email;
    private final SimpleStringProperty faculty;
    private final SimpleStringProperty room;

    // Constructor for creating new doctors (id will be generated by DB)
    public Doctor(String doctor_id,  String name, String faculty,  String phone, String email, String room) {
        super(doctor_id, name, phone); // Calls User(String nationalId, String name, String phone)
        this.email = new SimpleStringProperty(email);
        this.faculty = new SimpleStringProperty(faculty);
        this.room = new SimpleStringProperty(room);
    }

    // Constructor for retrieving doctors from DB (includes DB auto-incremented id)
    public Doctor(int id, String doctor_id, String name, String faculty, String phone, String email, String room) {
        super(id, doctor_id, name, phone); // Calls User(int id, String nationalId, String name, String phone)
        this.email = new SimpleStringProperty(email);
        this.faculty = new SimpleStringProperty(faculty);
        this.room = new SimpleStringProperty(room);
    }

    public Doctor(String doctor_id, String password, String name, String faculty,  String phone, String email, String room) {
        super(doctor_id, password, name, phone, true);// Calls User(String nationalId, String name, String phone)
        this.email = new SimpleStringProperty(email);
        this.faculty = new SimpleStringProperty(faculty);
        this.room = new SimpleStringProperty(room);
    }    

    // Getters for Doctor-specific properties
    public String getEmail() {
        return email.get();
    }

    public String getFaculty() {
        return faculty.get();
    }
    
    public String getRoom() {
        return room.get();
    }

    // Setters for Doctor-specific properties
    public void setemail(String value) {
        email.set(value);
    }

    public void setFaculty(String value) {
        faculty.set(value);
    }
    
    public void setRoom(String value) {
        room.set(value);
    }
   
    // Overriding abstract methods from User
    @Override
    public String getUserType() {
        return "Doctor";
    }

    @Override
    public String getSummary() {
        return "Doctor: " + getName() + " | Faculty: " + getFaculty() + " | Phone: " + getPhone();
    }

    // You can add SimpleStringProperty for inherited fields if needed for JavaFX binding
    // For example, if you want to bind the name to a TableColumn directly:
    public SimpleStringProperty nameProperty() {
        return new SimpleStringProperty(getName());
    }
    public SimpleStringProperty phoneProperty() {
        return new SimpleStringProperty(getPhone());
    }
}