package com.medisys.model;


public class Patient {
    private String username;
    private String password;
    private int id; //---auto increment
    private long patient_id; //cmnd cccd
    private String name;
    private String phone;
    private String dob;
    private String email;
    private String guardianRela;
    private String guardianPhone;
    private String guardianName;

    // Constructor for creating new patients (patient_id will be generated by DB)
    public Patient(String username, String password, long patient_id, String name, String phone, String dob) {
        this.username = username;
        this.password = password;
        this.patient_id = patient_id;
        this.name = name;
        this.phone = phone;
        this.dob = dob;
    }
    public Patient(String name, String phone, String dob) {
        this.name = name;
        this.phone = phone;
        this.dob = dob;
    }
    // Constructor for retrieving patients from DB (includes ID)

    public Patient(long patient_id, String name, String phone, String dob) {
        this.patient_id = patient_id;
        this.name = name;
        this.phone = phone;
        this.dob = dob;
    }

    public Patient(long patient_id, String name, String phone, String dob, String guardRela, String guardPhone, String guardName) {
        this.patient_id = patient_id;
        this.name = name;
        this.phone = phone;
        this.dob = dob;
        this.guardianName = guardName;
        this.guardianPhone = guardPhone;
        this.guardianRela = guardRela;
    }

    // Getters
    public long getId() {
        return patient_id;
    }

    public String getName() {
        return name;
    }

    public String getPhone() {
        return phone;
    }

    public String getGuardianName() {
        return guardianName;
    }

    public String getGuardPhone() {
        return guardianPhone;
    }

    public String getGuardianRela() {
        return guardianRela;
    }

    public String getDOB() {
        return dob;
    }

    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }
    // Setters (if you need to modify properties after creation, e.g., phone number)
    public void setName(String name) {
        this.name = name;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public void setID(int id) {  // set db_id
        this.id = id;
    }

    public void setDOB(String dob) {
        this.dob = dob;
    }

    public void setGuard(String guardRela, String guardName, String guardPhone) {
        this.guardianName = guardName;
        this.guardianPhone = guardPhone;
        this.guardianRela = guardRela;
    }
    // For debugging/printing
    @Override
    public String toString() {
        return "Patient{" +
               "id=" + patient_id +
               ", name='" + name + '\'' +
               ", phone='" + phone + '\'' +
               '}';
    }
}