package com.medisys.model;


public class Patient extends User{
    private String dob;
    //private String email;
    private String gender; // ADDED
    private String guardianRela;
    private String guardianPhone;
    private String guardianName;

    // // Constructor for creating new patients (patient_id will be generated by DB)
    // public Patient(String patient_id, String password, String name, String phone, String dob) {//, String email) {
    //     super(patient_id, password, name, phone, false); // Calls User(String nationalId, String name, String phone)
    //     this.dob = dob;
    //     // this.email = email;
    // }

    // // Constructor for retrieving patients from DB (includes DB auto-incremented id)
    // public Patient(int id, String patient_id, String password,  String name, String phone, String dob) {//, String email) {
    //     super(id, patient_id, password, name, phone, false); // Calls User(int id, String nationalId, String name, String phone)
    //     this.dob = dob;
    //     // this.email = email;
    // }

    // /* Needs review */
    // public Patient(String name, String phone, String dob) {
    //     super(-1, "", name, phone);
    //     this.dob = dob;
    // }

    // // Constructor without username/password for general patient info
    // public Patient(String patient_id, String name, String phone, String dob) { // String email) {
    //     super(patient_id, name, phone);
    //     this.dob = dob;
    //     // this.email = email;
    // }
    // // Additional constructor to include guardian info
    // public Patient(String patient_id, String name, String phone, String dob, String guardRela, String guardPhone, String guardName) {
    //     super(patient_id, name, phone);
    //     this.dob = dob;
    //     // this.email = email;
    //     this.guardianName = guardName;
    //     this.guardianPhone = guardPhone;
    //     this.guardianRela = guardRela;
    // }
    // public Patient(String patient_id, String password,  String name, String phone, boolean isDoctor) {
    //     super(patient_id, password, name, phone, isDoctor);
    // }

    // Constructor đầy đủ nhất, dùng để đọc từ DB (patient.txt)
    public Patient(int id, String nationalId, String password, String name, String phone, String dob, String gender, String guardRela, String guardName, String guardPhone) {
        super(nationalId, password, name, phone, false);
        this.id = id; // Set the DB auto-incremented ID
        this.dob = (dob != null) ? dob : "";
        this.gender = (gender != null) ? gender : "";
        this.guardianRela = (guardRela != null) ? guardRela : "";
        this.guardianName = (guardName != null) ? guardName : "";
        this.guardianPhone = (guardPhone != null) ? guardPhone : "";
    }
    
    // Constructor dùng khi đăng ký tài khoản mới (từ LoginAndRegisterController)
    private Patient(String nationalId, String password, String name, String phone, String gender) {
        super(nationalId, password, name, phone, false);
        this.dob = "";
        this.gender = (gender != null) ? gender : "";
        this.guardianRela = "";
        this.guardianName = "";
        this.guardianPhone = "";
    }

    // // Constructor dùng trong form đặt lịch cho bản thân
    // public Patient(String name, String phone, String dob, String gender) {
    //     super(-1, "", name, phone);
    //     this.dob = dob;
    //     this.gender = gender;
    // }

    // Constructor dùng trong form đặt lịch cho người khác (từ BookApmController)
    private Patient(String nationalId, String name, String phone, String dob, String gender, boolean isForBooking) {
        super(nationalId, name, phone);
        this.dob = (dob != null) ? dob : "";
        this.gender = (gender != null) ? gender : "";
    }

    // --- STATIC FACTORY METHODS ---
    
    /**
     * Creates a new Patient instance for the registration process.
     */
    public static Patient createForRegistration(String nationalId, String password, String name, String phone, String gender) {
        return new Patient(nationalId, password, name, phone, gender);
    }

    /**
     * Creates a new Patient instance when booking an appointment for someone else.
     */
    public static Patient createForOtherBooking(String nationalId, String name, String phone, String dob, String gender) {
        return new Patient(nationalId, name, phone, dob, gender, true);
    }

    // Getters for Patient-specific properties
    // public String getEmail() {
    //     return email;
    // }
    public String getGender() { return gender; }
    public String getGuardianName() { return guardianName; }
    public String getGuardPhone() { return guardianPhone; }
    public String getGuardianRela() { return guardianRela; }
    public String getDOB() { return dob; }

    // Setters for Patient-specific properties
    public void setGender(String gender) { this.gender = gender; }
    public void setDOB(String dob) { this.dob = dob; }
    // public void setEmail(String email) {
    //     this.email = email;
    // }
    public void setGuard(String guardRela, String guardName, String guardPhone) {
        this.guardianName = guardName;
        this.guardianPhone = guardPhone;
        this.guardianRela = guardRela;
    }

    // Overriding abstract methods from User
    @Override
    public String getUserType() {
        return "Patient";
    }

    @Override
    public String getSummary() {
        return "Patient: " + getName() + " | DOB: " + getDOB() + " | Phone: " + getPhone();
    }

    // For debugging/printing
    @Override
    public String toString() {
        return "Patient{" +
                "id=" + getId() + // national ID
                ", name='" + getName() + '\'' +
                ", phone='" + getPhone() + '\'' +
                '}';
    }
}